config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :questions do
    resources :answers
  end 

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :description, presence: true, length: {minimum: 50}

  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 40}, uniqueness: true
  validates :description, presence: true, length: {minimum: 150}

  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question

    if @answer.save
      redirect_to question_path(@answer.question)
      flash[:notice] = 'Answer was successfully created.'
    else
      render :'/questions/show'
      flash[:notice] = 'Answer was not created.'
    end

  end

  private

  def answer_params
    params.require(:answer).permit(:description, :best)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc)
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.order(created_at: :desc)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      flash[:notice] = 'Question was successfully created.'
      redirect_to question_path(@question)
    else
      flash[:notice] = "Failed to save question"
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update_attributes(question_params)
      flash[:notice] = 'Question was successfully edited.'
      redirect_to question_path(@question)
    else
      flash[:alert] = "Failed to save question"
      render :edit
    end
  end

  def destroy
    Question.find(params[:id]).destroy

    flash[:notice] = "Question was deleted!"
    redirect_to questions_path
  end



  private

  def question_params
    params.require(:question).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= form_for([@question, @answer]) do |f| %>
  <% if @answer.errors.any? %>
    <div>

      <h2>
        <%= pluralize(@answer.errors.count, "error") %> Answer could not be saved!
      </h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

  <div class="field" id="description">
    <%= f.label :description, "Answer" %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Answer" %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div>

      <h2>
        <%= pluralize(@question.errors.count, "error") %> Question could not be saved!
      </h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

  <div class="field" id="title">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field" id="description" >
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/questions/edit.html.erb
<h2><%= @question.title %></h2>

<%= form_for(@question) do |f| %>

  <div class="field" id="description" value="#{@question.description}">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
<br>
<h4><%= link_to "DELETE", @question, method: :delete, data: { confirm: "You sure?" } %></h4> 

app/views/questions/index.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<h2>Questions</h2>

<ul>
  <% @questions.each do |question| %>
  <li>
    <%= link_to question.title, question_path(question) %>
    <%= question.description %>
    <%= question.created_at %>
    <% if question.created_at != question.updated_at %>
      <%= question.updated_at %>
    <% end %>
  </li>
  <% end %>
</ul>

<h3><%= link_to "New Question Form", new_question_path %></h3>

app/views/questions/new.html.erb
<h1>New Question</h1>

<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= render 'form' %>

<%= link_to "Back", questions_path %>

app/views/questions/show.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<p>
  <strong>Title: </strong>
  <%= @question.title %><br>
  <strong>Description: </strong>
  <%= @question.description %><br>
  <strong>Created At: </strong>
  <%= @question.created_at %><br>
  <% if @question.created_at != @question.updated_at %>
    <strong>Updated At: </strong>
    <%= @question.updated_at %><br>
  <% end %>

  <br>
  <% if !@answers.blank? %>
    <strong>Answers: </strong>
    <ol>
      <% @answers.each do |a, index| %>
        <li><%= a.description %></li>
      <% end %>
    </ol>
  <% end %>
</p>

<%= render 'answers/form' %>
<br>
<h3><%= link_to "Edit Question", edit_question_path(@question.id) %></h3>
<h3><%= link_to "Question Index", questions_path %></h3>